
networks:
    omm:
        name: omm

services:

    gateway:
        hostname: gateway
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: 50M
        tty: true
        
        build:
            context: ./gateway/
        image: gcc:latest
        volumes:
            - ./gateway:/gateway
        container_name: gateway
        command: bin/bash /gateway/start.sh
        depends_on:
            - dribbling
            - infortunio
            - tiro
        ports: 
            - 8080:8080
        networks:
            - omm

    dribbling:
        hostname: dribbling
        tty: true
        build:
            context: ./dribbling/
        image: gcc:latest
        volumes:
            - ./dribbling:/dribbling
        container_name: dribbling
        command: bin/bash /dribbling/start.sh
        networks:
            - omm
        ports: 
            - 8033:8033

    infortunio:
        hostname: infortunio
        tty: true
        build:
            context: ./infortunio/
        image: gcc:latest
        volumes:
            - ./infortunio:/infortunio
        container_name: infortunio
        command: bin/bash /infortunio/start.sh
        networks:
            - omm
        ports: 
            - 8041:8041

    tiro:
        hostname: tiro
        tty: true
        build:
            context: ./tiro/
        image: gcc:latest
        volumes:
            - ./tiro:/tiro
        container_name: tiro
        command: bin/bash /tiro/start.sh
        networks:
            - omm
        ports: 
            - 8077:8077